lives:
  # The amount of lives a player starts with
  default: 5
  # The maximum amount of lives a player can have
  max: 10
  # The amount of lives that puts the player into spectator
  min: 0

# The causes that will result in a player to losing a life, leave empty for all causes
# Available causes: https://helpch.at/docs/[MC VERSION]/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html
death-causes: []

# Whether to enable killers gaining a life when they kill a player
stealing: true

# The commands that will be executed when a player loses all their lives (executed by the console)
# %player% - The player that lost all their lives
# %killer% - The player that got the final kill on %player%. If %player% died from a non-player cause, any commands that use %killer% will be ignored
punishment-commands:
  # Executed right when the player dies
  death: []
  # Executed when the player respawns
  respawn:
    - "gamemode spectator %player%"
