name: ${name}
description: ${description}
authors:
  - srnyx
website: https://srnyx.com

main: ${group}.limitedlives.LimitedLives
version: ${version}
api-version: 1.13

softdepend:
  - PlaceholderAPI
  - WorldGuard

commands:
  lives:
    description: Manage the lives of a player
  lifereload:
    description: Reloads the plugin
    aliases:
      - llreload
      - limitedlivesreload
    permission: limitedlives.reload

permissions:
  limitedlives.reload:
    description: Allows the player to use /lifereload
  limitedlives.get.self:
    description: Allows the player to use /lives get on themselves
  limitedlives.get.other:
    description: Allows the player to use /lives get on others
  limitedlives.set.self:
    description: Allows the player to use /lives set on themselves
  limitedlives.set.other:
    description: Allows the player to use /lives set on others
  limitedlives.add.self:
    description: Allows the player to use /lives add on themselves
  limitedlives.add.other:
    description: Allows the player to use /lives add on others
  limitedlives.remove.self:
    description: Allows the player to use /lives remove on themselves
  limitedlives.remove.other:
    description: Allows the player to use /lives remove on others
  limitedlives.withdraw.self:
    description: Allows the player to use /lives withdraw on themselves
  limitedlives.withdraw.other:
    description: Allows the player to use /lives withdraw on others
  limitedlives.give:
    description: Allows the player to use /lives give
  limitedlives.max.#:
    description: Gives the player their own specific max lives
    default: false
