blank_issues_enabled: true
contact_links:
  - name: 💬 Support
    url: https://srnyx.com/discord
    about: "If you need help with the plugin or have a question please join the Discord server and ask there."
