name: Publish
on:
  push:
    branches:
      - master
    paths:
      - 'gradle/**'
      - 'src/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'gradlew'
      - 'gradlew.bat'
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    uses: srnyx/tools/.github/workflows/publish.yml@main
    secrets: inherit
