name: Build [PR]
on:
  pull_request:
    paths:
      - 'gradle/**'
      - 'src/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'gradlew'
      - 'gradlew.bat'
  workflow_dispatch:

jobs:
  build:
    uses: srnyx/tools/.github/workflows/build.yml@main
    with:
      name: Limited Lives
