name: Publish
on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  publish:
    uses: srnyx/tools/.github/workflows/publish.yml@main
    with:
      modrinth: LvTKDASD
      curseforge: 846826
      loaders: |
        purpur
        paper
        spigot
        folia
    secrets: inherit
    permissions:
      contents: write
